### ISSUE TITLE
Clipping and misalignment of welcome buttons

### ISSUE THREAD

**Issue by thepaullee** [uOttaHack/2018.uottahack.ca#8]

**Comment by arsanig** [comment]
Fixed by PR #11

**Comment by thepaullee** [comment]
The buttons still seem to clip depending on the dimensions of the window, zoom in and out to see what I mean

**Comment by arsanig** [comment]
Okay, I see what you're saying, I'm pretty confident it's because of this in hero.html they're links:

`<a href="{{ link.href }}">{{ link.text }}</a>`

I think if we made them buttons they won't clip

**Comment by thepaullee** [comment]
Fixed in PR #13
